import os

UPSTOX_ACCESS_TOKEN = os.getenv("UPSTOX_ACCESS_TOKEN")

SPOT_PRICE = 22500
RISK_FREE_RATE = 0.065
TIME_TO_EXPIRY = 5/252

MISPRICING_THRESHOLD = 5
IRON_CONDOR_DISTANCE = 200

LOTTERY_PREMIUM_MAX = 20
LOTTERY_DISTANCE = 500
